### PR TITLE
chore(CI): make smithy diff checker smarter

### PR DESCRIPTION
**Pull request by josecorella**
_Issue #, if available:_

_Description of changes:_

_Squash/merge commit message, if applicable:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by texastony** [comment]
When I was thinking about how to do this, I envisioned having GH respond to code reviews, tagging both the author and the reviewer. 

That way, the process only responds to actual reviews.

**Comment by lucasmcdonald3** [comment]
testing

**Review by lucasmcdonald3 — COMMENTED** [review]
testing

**Review by lucasmcdonald3 — COMMENTED** [review]
test

**Review by lucasmcdonald3 — APPROVED** [review]
Approving assuming this needs to be merged in to run

**Pull request merged**
