### PR TITLE
fix: Move Java helper methods out of extern class

### PR DESCRIPTION
**Pull request by robin-aws**
_Description of changes:_

I added these as a migration workaround for upgrading the Dafny version, but as a side effect it made `HMac` a mixed Dafny/native class when it wasn't intended to be, and this isn't supported on all target languages (e.g. Go). Easy fix to move them out of the class to the surrounding module instead.

_Squash/merge commit message, if applicable:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by texastony** [comment]
Waiting on results of https://github.com/aws/aws-database-encryption-sdk-dynamodb/actions/runs/11333537614

**Comment by texastony** [comment]
@robin-aws @josecorella This Branch is failing the "does not break DB-ESDK" check:
https://github.com/aws/aws-database-encryption-sdk-dynamodb/actions/runs/11333537614

Question: @josecorella Did I run the check correctly?

**Review by texastony — CHANGES_REQUESTED** [review]
Blocking until we figure out if this works with DB-ESDK or not.
https://github.com/aws/aws-database-encryption-sdk-dynamodb/actions/runs/11333537614/job/31517906552

**Comment by texastony** [comment]
Tried again with the a newer manual workflow: https://github.com/aws/aws-database-encryption-sdk-dynamodb/actions/runs/11333611590

**Comment by robin-aws** [comment]
Thanks @texastony! @josecorella would it be doable to run the "does not break DB-ESDK" check in the CI of this project?

**Pull request merged**
